### PR TITLE
Tasks for Internship

### PR DESCRIPTION
**Pull request by hsharma151197**
1. Added GitHub Ribbon
2. Added Report Button

### CODE REVIEW

**Comment by sachinjain024** [comment]
@hsharma151197 Here is my feedback - 
1. Fork Me Banner should come on Notifications Page (Page where we show all notifications with 5 tabs). So please move it to the left top on Notifications Page.
2. I think the "Report" button should be always visible. I would prefer to show the "Report Bug" button on the right-hand side of the top toolbar.

Can you make these changes and update the PR.

**Comment by hsharma151197** [comment]
Ok Sir I will, give me some more time

**Comment by hsharma151197** [comment]
Sir plz take a look again

**Comment by sachinjain024** [comment]
@hsharma151197 Report Bug is not coming at right place. Here is a screenshot from my computer

screenshot 2019-02-16 11 43 45

It should come on the right hand of the black bar. Please discuss me if there are doubts. 

And, Can you please improve your commit messages? Try to make them more meaningful in terms of what is contained in the changes.

**Comment by hsharma151197** [comment]
sry sir actually, in my pc it is showing correctly wait.
screenshot from 2019-02-16 13-03-51
just give me some time again for media queries,
and ok i will wrote some meaning messages

**Comment by sachinjain024** [comment]
@hsharma151197 Let me clarify a bit more. We should place the "Report Bug" button on the side of the black colored bar/header where `StackEye - Keep Watching Keep Learning` is written. Place `Report bug` button on the extreme right of that bar.

Feel free to call me if you have ay doubts.

**Comment by hsharma151197** [comment]
okay sir, wait

**Comment by hsharma151197** [comment]
Sir, 
a div tag and a button tag has been added at header in **src/pages/index.html** with some classes already present in project, and some changes in **src/pages/np.css**

**Comment by sachinjain024** [comment]
@hsharma151197 I have merged this branch in master using squash option to make git history clean and also modified the commit message. Closing this pull request. Thank you for working on this one. I will call you to discuss further steps.

**Pull request closed without merging**
